version: "3.10"
services:
  db:
    container_name: "test_db"
    image: postgres:15.1-alpine
    restart: always
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - menu_network_test

  test_web:
    container_name: "test_web"
    image: test_web
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pytest -v"
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - menu_network_test

networks:
  menu_network_test:
    driver: bridge

