version: "3"
services:
  test_app:
    container_name: "test_app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: test_database
      POSTGRES_PORT: 5432
      POSTGRES_DB: test_db
    command: pytest -v
    ports:
      - "8001:8000"
    depends_on:
      test_database:
        condition: service_healthy
    networks:
      - menu_network_test


  test_database:
    image: postgres:15.1-alpine
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - menu_network_test

networks:
  menu_network_test:
    driver: bridge

