version: "3"
services:
  test_app:
    container_name: "test_app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file: .env_test
    command: pytest -v
    ports:
      - "8001:8000"
    depends_on:
      test_database:
        condition: service_healthy
    networks:
      - menu_network_test

  test_database:
    image: postgres:15.1-alpine
    restart: always
    env_file: .env_test
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - menu_network_test

  test_cache:
    image: redis:latest
    env_file: .env_test
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - menu_network_test

networks:
  menu_network_test:
    driver: bridge
