[tool.poetry]
name = "menu"
version = "0.1.0"
description = ""
authors = ["timosii <holdcarter@holdcarter.ru>"]
packages = [{include = "menu_app"}]

[tool.poetry.dependencies]
python = "^3.10"
SQLAlchemy = "^2.0.19"
postgres = "^4.0"
sqlalchemy-orm = "^1.2.10"
fastapi = "^0.100.0"
POS

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
